### ISSUE TITLE
Set default format

### ISSUE THREAD

**Issue by Chopper1337** [soystemd/mpv-selectformat#2]
Is it possible to set a default format based on resolution?

**Comment by demurky** [comment]
You mean something like *"av1 for resolutions less than 480p, vp9 for resolutions less than 720p, x264 for the rest"*?

**Comment by Chopper1337** [comment]
ideally just being able to default to a resolution like 1080p if the option is available

**Comment by demurky** [comment]
For setting a default resolution, you can configure mpv's `ytdl-format` option.

See the docs of mpv and youtube-dl for more info, but as an example, you can instruct mpv to load the highest resolution up to 1080p by putting this line in mpv's config file: 

```
ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]/bestvideo+bestaudio/best
```

**Comment by Chopper1337** [comment]
Thank you. I thought it would need to be done in the lua.

Thanks for the lua also :)

Closing.
