### ISSUE TITLE
Error when trying to change format

### ISSUE THREAD

**Issue by vovchikzd** [soystemd/mpv-selectformat#3]
When try to change format while streaming a video from youtube or twitch, this error occurs
![image](https://github.com/koonix/mpv-selectformat/assets/132217671/1797484a-9c6e-44a6-96e8-446e11b0b52b)

so, just for test, I changed this line of [selectformat.lua](https://github.com/koonix/mpv-selectformat/blob/master/selectformat.lua#L996) to
``` lua
mp.commandv("loadfile", url, "replace", math.floor(pos))
```
and everything worked on both youtube and twitch (didn't try the other ones).

Don't know what other parts of code it may affect.

mpv v0.38.0-dirty

**Comment by demurky** [comment]
Looks like mpv changed the structure of `loadfile`'s arguments in mpv >= v0.38.0

The correct change would actually be

```
mp.commandv("loadfile", url, "replace", 0, "start=+" .. pos)
```

**Comment by demurky** [comment]
Should be fixed now.
